package errorHandler;

public enum ErrorType {
    FOLDER_IS_FULL, NOT_A_STORAGE, UNAUTHORIZED_ACTION, NOT_CONNECTED, STORAGE_IS_FULL, FILE_DOES_NOT_EXISTS,
    CANNOT_CHANGE_ROOT, FILE_NOT_CREATED
}
